[package]
name = "rustbot"
version = "0.1.0"
authors = ["Daniel Griffen <daniel@griffen.io>"]
edition = "2018"

[dependencies]
irc = "0.13"
chrono = "0.4"
diesel = { version = "1.0", features = ["sqlite", "chrono"] }
failure = "0.1"
toml = "0.4"
serde = { version = "1.0", features = ["derive"] }