[package]
name = "irc-bot-types"
version = "0.1.0"
authors = ["Daniel Griffen <daniel@griffen.io>"]
edition = "2018"

[dependencies]
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.4"
irc = "0.13"
state = "0.4"