[lib]
proc-macro = true

[package]
name = "nestor_codegen"
version = "0.0.1"
authors = ["Daniel Griffen <daniel@griffen.io>"]
edition = "2018"

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"