[connection]
owners = ["dgriffen"]
nickname = "rustybot_testing"
server = "irc.mozilla.org"
channels = ["#rust-offtopic"]
source = "https://github.com/dgriffen/rustybot"

[bot]
admins = ["dgriffen"]
blacklisted_users = ["rustbot"]
database_url = "rustybot.sqlite"
command_indicator = ["&&"]
alias_depth = 3
contact = "daniel+rustybot@griffen.io"
github_auth = { username = "daniel@griffen.io", password = "b5d9878b02ad156cf31d133ac6abaa79564a6a76" }